name: Build and Release

on:
  push:
    branches: [ main ]
  create:
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare Go dependencies
      run: go mod tidy
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    
    - name: Prepare Node.js dependencies
      run: cd web && npm i && cd ..
    
    - name: Build
      run: ./make.sh
    
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.xz

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare Go dependencies
      run: go mod tidy
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    
    - name: Prepare Node.js dependencies
      run: cd web && npm i && cd ..
    
    - name: Build
      run: ./make.sh

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*.tar.xz

  release:
    needs: [build-linux,build-mac]
    if: ${{ startsWith(github.ref,'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: Create release
        uses: docker://antonyurchenko/git-release:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "none"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            *.tar.xz