name: Go

on:
  push:
    branches: [ main ]
  create:
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare Go dependencies
      run: go mod tidy
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    
    - name: Prepare Node.js dependencies
      run: cd web && npm i && cd ..
    
    - name: Build
      run: ./make.sh

    - if: ${{ startsWith(github.ref,'refs/tags/') }}
      name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - if: ${{ startsWith(github.ref,'refs/tags/'') }}
      ame: Update release
      uses: johnwbyrd/update-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ${{ format("GoFile-{0}-Linux-x86_64.tar.xz",steps.tag.outputs.tag}}

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare Go dependencies
      run: go mod tidy
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    
    - name: Prepare Node.js dependencies
      run: cd web && npm i && cd ..
    
    - name: Build
      run: ./make.sh
