name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Prepare Go dependencies
      run: go mod tidy
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    
    - name: Prepare Node.js dependencies
      run: cd web && npm i && cd ..
    
    - name: Build
      run: ./make.sh
